// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvC6dNX98chYxQgRZa2qKJuWWMLQnyqw',
    appId: '1:809821639133:android:58d314a98318b32fc0e634',
    messagingSenderId: '809821639133',
    projectId: 'la-profecia-7e09f',
    storageBucket: 'la-profecia-7e09f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktmUx5MHA3zNsCFP4LLZBvXTMluAX58k',
    appId: '1:809821639133:ios:da51c74a24e171d5c0e634',
    messagingSenderId: '809821639133',
    projectId: 'la-profecia-7e09f',
    storageBucket: 'la-profecia-7e09f.firebasestorage.app',
    androidClientId:
        '809821639133-482muaq18rd9fsok8un8eer0gi96vdcd.apps.googleusercontent.com',
    iosClientId:
        '809821639133-j2bgu86u52bssac9se06357d7615mkva.apps.googleusercontent.com',
    iosBundleId: 'com.laprofecia.verdadoreto',
  );
}
